language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t gonzalo/docker-react -f Dockerfile.dev .
script:
        - docker run -e CI=true gonzalo/docker-react npm run test -- --coverage
